import React from 'react'
import SectionTitle from '../Components/UiComponents/SectionTitle'

export default function PrivacyPolicies() {
    return (
        <main>
            <section className='py-10 lg:py-20 xl:py-28 bg-BGcolor'>
                <div className="container mx-auto px-4">
                    <SectionTitle title="PRIVACY POLICY" />
                    <h3 className='text-xl sm:text-2xl font-semibold text-Tcolor mb-2'>Last updated May 10, 2024</h3>
                    <p>{`This privacy notice for DIGITAL WAVE IT SOLUTIONS PRIVATE LIMITED (doing business as DiggiAssist) ('we', 'us', or 'our'), describes how and why we might collect, store, use, and/or share ('process') your information when you use our services ('Services'), such as when you: Download and use our mobile application (DiggiAssist), or any other application of ours that links to this privacy notice Engage with us in other related ways, including any sales, marketing, or events Questions or concerns?Â Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have any questions or concerns, please contact us at info@digitalwaveitsolution.com.`}</p>
                    <div className='space-y-10 mt-5 lg:mt-10'>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>SUMMARY OF KEY POINTS</h3>
                            <p>{`This summary provides key points from our privacy notice, but you can find out more details about any of these topics by clicking the link following each key point or by using ourÂ table of contentsÂ below to find the section you are looking for. What personal information do we process? When you visit, use, or navigate our Services, we may process personal information depending on how you interact with us and the Services, the choices you make, and the products and features you use. Learn more aboutÂ personal information you disclose to us. Do we process any sensitive personal information? We do not process sensitive personal information. Do we receive any information from third parties? We do not receive any information from third parties. How do we process your information? We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so. Learn more aboutÂ how we process your information. In what situations and with which parties do we share personal information? We may share information in specific situations and with specific third parties. Learn more aboutÂ when and with whom we share your personal information. How do we keep your information safe? We have organisational and technical processes and procedures in place to protect your personal information. However, no electronic transmission over the internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorised third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Learn more aboutÂ how we keep your information safe. What are your rights? Depending on where you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information. Learn more aboutÂ your privacy rights. How do you exercise your rights? The easiest way to exercise your rights is by submitting aÂ data subject access request, or by contacting us. We will consider and act upon any request in accordance with applicable data protection laws. Want to learn more about what we do with any information we collect?Â Review the privacy notice in full.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>TABLE OF CONTENTS</h3>
                            <ul className='space-y-3 my-4'>
                                <li>1. WHAT INFORMATION DO WE COLLECT?</li>
                                <li>2. HOW DO WE PROCESS YOUR INFORMATION?</li>
                                <li>3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</li>
                                <li>4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</li>
                                <li>5. HOW DO WE HANDLE YOUR SOCIAL LOGINS?</li>
                                <li>6. HOW LONG DO WE KEEP YOUR INFORMATION?</li>
                                <li>7. HOW DO WE KEEP YOUR INFORMATION SAFE?</li>
                                <li>8. WHAT ARE YOUR PRIVACY RIGHTS?</li>
                                <li>9. CONTROLS FOR DO-NOT-TRACK FEATURES</li>
                                <li>10. DO WE MAKE UPDATES TO THIS NOTICE?</li>
                                <li>11. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</li>
                                <li>12. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</li>
                            </ul>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>1. WHAT INFORMATION DO WE COLLECT?</h3>
                            <h4 className='text-lg text-Tcolor'>Personal information you disclose to us</h4>
                            <p>{`In Short:Â We collect personal information that you provide to us. We collect personal information that you voluntarily provide to us when you register on the Services,Â express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us. Personal Information Provided by You. The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make, and the products and features you use. The personal information we collect may include the following:`}</p>
                            <ul className='space-y-3 my-4'>
                                <li>names</li>
                                <li>phone numbers</li>
                                <li>email addresses</li>
                                <li>mailing addresses</li>
                                <li>job titles</li>
                                <li>contact or authentication data</li>
                                <li>billing addresses</li>
                                <li>debit/credit card numbers</li>
                            </ul>
                            <p>{`Sensitive Information. We do not process sensitive information. Payment Data. We may collect data necessary to process your payment if you make purchases, such as your payment instrument number, and the security code associated with your payment instrument. All payment data is stored by Cashfree. You may find their privacy notice link(s) here: https://digitalwaveitsolutions.s3.ap-south-1.amazonaws.com/SoftLand/privacy-policies.html. Social Media Login Data.Â We may provide you with the option to register with us using your existing social media account details, like your Facebook, Twitter, or other social media account. If you choose to register in this way, we will collect the information described in the section called 'HOW DO WE HANDLE YOUR SOCIAL LOGINS?' below. Application Data. If you use our application(s), we also may collect the following information if you choose to provide us with access or permission: Geolocation Information. We may request access or permission to track location-based information from your mobile device, either continuously or while you are using our mobile application(s), to provide certain location-based services. If you wish to change our access or permissions, you may do so in your device's settings. Mobile Device Access. We may request access or permission to certain features from your mobile device, including your mobile device's camera, contacts, reminders, sms messages, and other features. If you wish to change our access or permissions, you may do so in your device's settings. Push Notifications. We may request to send you push notifications regarding your account or certain features of the application(s). If you wish to opt out from receiving these types of communications, you may turn them off in your device's settings. This information is primarily needed to maintain the security and operation of our application(s), for troubleshooting, and for our internal analytics and reporting purposes. All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.`}</p>
                            <h4 className='text-lg text-Tcolor font-semibold my-3'>Information automatically collected</h4>
                            <p>{`In Short:Â Some information â€” such as your Internet Protocol (IP) address and/or browser and device characteristics â€” is collected automatically when you visit our Services. We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information. This information is primarily needed to maintain the security and operation of our Services, and for our internal analytics and reporting purposes. Like many businesses, we also collect information through cookies and similar technologies. You can find out more about this in our Cookie Notice: https://digitalwaveitsolutions.s3.ap-south-1.amazonaws.com/SoftLand/cookies.html. The information we collect includes:`}</p>
                            <ul className='space-y-3 my-4'>
                                <li>{`Log and Usage Data. Log and usage data is service-related, diagnostic, usage, and performance information our servers automatically collect when you access or use our Services and which we record in log files. Depending on how you interact with us, this log data may include your IP address, device information, browser type, and settings and information about your activity in the ServicesÂ (such as the date/time stamps associated with your usage, pages and files viewed, searches, and other actions you take such as which features you use), device event information (such as system activity, error reports (sometimes called 'crash dumps), and hardware settings).`}</li>
                                <li>{`Device Data. We collect device data such as information about your computer, phone, tablet, or other device you use to access the Services. Depending on the device used, this device data may include information such as your IP address (or proxy server), device and application identification numbers, location, browser type, hardware model, Internet service provider and/or mobile carrier, operating system, and system configuration information.`}</li>
                                <li>{`Location Data. We collect location data such as information about your device's location, which can be either precise or imprecise. How much information we collect depends on the type and settings of the device you use to access the Services. For example, we may use GPS and other technologies to collect geolocation data that tells us your current location (based on your IP address). You can opt out of allowing us to collect this information either by refusing access to the information or by disabling your Location setting on your device. However, if you choose to opt out, you may not be able to use certain aspects of the Services.`}</li>
                            </ul>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>2. HOW DO WE PROCESS YOUR INFORMATION?</h3>
                            <p>{`In Short:Â We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.`}
                            </p>
                            <h4 className='text-lg text-Tcolor font-semibold my-3'>We process your personal information for a variety of reasons, depending on how you interact with our Services, including:
                            </h4>
                            <ul className='space-y-3 my-4'>
                                <li>{`To facilitate account creation and authentication and otherwise manage user accounts.Â We may process your information so you can create and log in to your account, as well as keep your account in working order.`}</li>
                                <li>{`To deliver and facilitate delivery of services to the user.Â We may process your information to provide you with the requested service.`}</li>
                                <li>{`To respond to user inquiries/offer support to users.Â We may process your information to respond to your inquiries and solve any potential issues you might have with the requested service.`}</li>
                                <li>{`To fulfil and manage your orders.Â We may process your information to fulfil and manage your orders, payments, returns, and exchanges made through the Services.`}</li>
                                <li>{`To request feedback.Â We may process your information when necessary to request feedback and to contact you about your use of our Services.`}</li>
                                <li>{`To deliver targeted advertising to you.Â We may process your information to develop and display personalised content and advertising tailored to your interests, location, and more. For more information see our Cookie Notice: https://digitalwaveitsolutions.s3.ap-south-1.amazonaws.com/SoftLand/cookies.html.`}</li>
                                <li>{`To protect our Services. We may process your information as part of our efforts to keep our Services safe and secure, including fraud monitoring and prevention.`}</li>
                            </ul>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</h3>
                            <p>In Short:Â We may share information in specific situations described in this section and/or with the following third parties. We may need to share your personal information in the following situations:</p>
                            <ul className='space-y-3 my-4'>
                                <li>{`Business Transfers. We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.`}</li>
                                <li>{`When we use Google Analytics.Â We may share your information with Google Analytics to track and analyse the use of the Services. The Google Analytics Advertising Features that we may use include: Remarketing with Google Analytics. To opt out of being tracked by Google Analytics across the Services, visit https://tools.google.com/dlpage/gaoptout. You can opt out of Google Analytics Advertising Features through Ads Settings and Ad Settings for mobile apps. Other opt out means include http://optout.networkadvertising.org/ and http://www.networkadvertising.org/mobile-choice. For more information on the privacy practices of Google, please visit the Google Privacy & Terms page.`}</li>
                                <li>{`When we use Google Maps Platform APIs. We may share your information with certain Google Maps Platform APIs (e.g. Google Maps API, Places API). We obtain and store on your device ('cache') your location. You may revoke your consent anytime by contacting us at the contact details provided at the end of this document.`}</li>
                                <li>{`Offer Wall.Â Our application(s) may display a third-party hosted 'offer wall'. Such an offer wall allows third-party advertisers to offer virtual currency, gifts, or other items to users in return for the acceptance and completion of an advertisement offer. Such an offer wall may appear in our application(s) and be displayed to you based on certain data, such as your geographic area or demographic information. When you click on an offer wall, you will be brought to an external website belonging to other persons and will leave our application(s). A unique identifier, such as your user ID, will be shared with the offer wall provider in order to prevent fraud and properly credit your account with the relevant reward.`}</li>
                            </ul>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</h3>
                            <p>{`In Short:Â We may use cookies and other tracking technologies to collect and store your information. We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Notice: https://digitalwaveitsolutions.s3.ap-south-1.amazonaws.com/SoftLand/cookies.html.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>5. HOW DO WE HANDLE YOUR SOCIAL LOGINS?</h3>
                            <p>{`In Short:Â If you choose to register or log in to our Services using a social media account, we may have access to certain information about you. Our Services offer you the ability to register and log in using your third-party social media account details (like your Facebook or Twitter logins). Where you choose to do this, we will receive certain profile information about you from your social media provider. The profile information we receive may vary depending on the social media provider concerned, but will often include your name, email address, friends list, and profile picture, as well as other information you choose to make public on such a social media platform. We will use the information we receive only for the purposes that are described in this privacy notice or that are otherwise made clear to you on the relevant Services. Please note that we do not control, and are not responsible for, other uses of your personal information by your third-party social media provider. We recommend that you review their privacy notice to understand how they collect, use, and share your personal information, and how you can set your privacy preferences on their sites and apps.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>6. HOW LONG DO WE KEEP YOUR INFORMATION?</h3>
                            <p>{`In Short:Â We keep your information for as long as necessary to fulfil the purposes outlined in this privacy notice unless otherwise required by law. We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than Â  the period of time in which users have an account with us.Â When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymise such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>7. HOW DO WE KEEP YOUR INFORMATION SAFE?</h3>
                            <p>{`In Short:Â We aim to protect your personal information through a system of organisational and technical security measures. We have implemented appropriate and reasonable technical and organisational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorised third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Although we will do our best to protect your personal information, transmission of personal information to and from our Services is at your own risk. You should only access the Services within a secure environment.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>8. WHAT ARE YOUR PRIVACY RIGHTS?</h3>
                            <p>{`In Short:Â Â You may review, change, or terminate your account at any time. Withdrawing your consent: If we are relying on your consent to process your personal information, which may be express and/or implied consent depending on the applicable law, you have the right to withdraw your consent at any time. You can withdraw your consent at any time by contacting us by using the contact details provided in the section 'HOW CAN YOU CONTACT US ABOUT THIS NOTICE?' below. However, please note that this will not affect the lawfulness of the processing before its withdrawal nor, when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.`}</p>
                            <h4 className='text-lg text-Tcolor font-semibold my-3'>Account Information</h4>
                            <p>{`If you would at any time like to review or change the information in your account or terminate your account, you can: Log in to your account settings and update your user account. Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our legal terms and/or comply with applicable legal requirements. Cookies and similar technologies: Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our Services. For further information, please see our Cookie Notice: https://digitalwaveitsolutions.s3.ap-south-1.amazonaws.com/SoftLand/cookies.html. If you have questions or comments about your privacy rights, you may email us at info@digitalwaveitsolution.com.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>9. CONTROLS FOR DO-NOT-TRACK FEATURES</h3>
                            <p>{`Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track ('DNT') feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage no uniform technology standard for recognising and implementing DNT signals has been finalised. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>10. DO WE MAKE UPDATES TO THIS NOTICE?</h3>
                            <p>{`In Short:Â Yes, we will update this notice as necessary to stay compliant with relevant laws. We may update this privacy notice from time to time. The updated version will be indicated by an updated 'Revised' date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.`}</p>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>11. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</h3>
                            <p>{`If you have questions or comments about this notice, you may email us at info@digitalwaveitsolution.com orÂ contact us by post at:`}</p>
                            <ul className='space-y-3 my-4'>
                                <li>DIGITAL WAVE IT SOLUTIONS PRIVATE LIMITED</li>
                                <li>39 mitra nagar , khirni phatak jhotwara jaipur, Rajasthan 302012 India</li>
                            </ul>
                        </div>
                        <div>
                            <h3 className='text-xl ms:text-2xl font-semibold text-Tcolor mb-3'>12. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</h3>
                            <p>{`You have the right to request access to the personal information we collect from you, change that information, or delete it. To request to review, update, or delete your personal information, please fill out and submit aÂ data subject access request.`}</p>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    )
}
